name: yinruifang 
url: https://yinrui-fang.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8

# Base pathname for links.
base: ''

education:
  - institution: "某小学"
    degree: "小学教育"
    description: "在这里完成了基础教育。"
    start_date: "2010年9月"
    end_date: "2016年6月"

  - institution: "某中学"
    degree: "初中教育"
    description: "在这里学习了初中课程。"
    start_date: "2016年9月"
    end_date: "2019年6月"

  - institution: "某高中"
    degree: "高中教育"
    description: "在这里完成了高中学业。"
    start_date: "2019年9月"
    end_date: "2022年6月"

  - institution: "某大学"
    degree: "计算机科学学士"
    description: "在这里获得计算机科学学位。"
    start_date: "2022年9月"
    end_date: "2026年6月"

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 过往经历 Personal experience
    link: /experience.html
  - title: 论文 Publication
    link: /publication.html
