name: yinruifang 
url: https://yinrui-fang.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8

# Base pathname for links.
base: ''

education:
  - institution: "阳曲县新阳街小学"
    degree: "小学教育"
    description: "在这里完成了基础教育。"
    start_date: "2008年9月"
    end_date: "2014年6月"

  - institution: "阳曲县第二中学"
    degree: "初中教育"
    description: "在这里学习了初中课程。"
    start_date: "2014年9月"
    end_date: "2017年6月"

  - institution: "山西大学附属中学"
    degree: "高中教育"
    description: "在这里完成了高中学业。"
    start_date: "2017年9月"
    end_date: "2020年6月"
    
  - institution: "北京师范大学"
    degree: "数学学士"
    description: "在这里获得学士学位。"
    start_date: "2020年9月"
    end_date: "2024年6月"
    url: "https://www.bnu.edu.cn/"
    
# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 过往经历 Personal experience
    link: /experience.html
  - title: 论文 Publication
    link: /publication.html
